# Sourcery Configuration for Dev-Toolkit
# ULTRA-RESTRICTIVE: Only review critical code files to avoid diff limits

# Paths to include in reviews (ONLY essential code)
path_patterns:
  - "bin/*.sh"                       # Command executables only
  - "lib/core/*.sh"                  # Core libraries only
  - "install.sh"                     # Installation script

# Paths to exclude from reviews (EVERYTHING else)
ignore_patterns:
  - "**"                             # Exclude everything by default
  - "!bin/*.sh"                      # Except command executables
  - "!lib/core/*.sh"                 # Except core libraries
  - "!install.sh"                    # Except installation script

# GitHub integration settings
github:
  # Only review changed files, not entire PR
  sourcery_branch: main
  
  # Skip reviews for documentation-only PRs
  skip_docs_only: true
  
  # Only review files with actual code changes (not just whitespace)
  ignore_whitespace: true
  
  # Skip reviews for very small changes (less than 15 lines)
  min_lines_changed: 15
  
  # Skip reviews for very large changes (more than 100 lines)
  max_lines_changed: 100
  
  # Only review files with significant changes (not just formatting)
  significant_changes_only: true

# Shell-specific settings
shell:
  # Use bash for shell script analysis
  shell_type: "bash"
  
  # Enable strict mode checking
  strict_mode: true

# Review settings
review:
  # Only review critical issues (not style suggestions)
  severity_threshold: "high"
  
  # Skip reviews for test files (they change frequently)
  skip_test_files: true
  
  # Skip reviews for configuration files
  skip_config_files: true